Repository SukBakJi/SukBakJi-Server, pull requests merged in 2024-07, with the labels that each got.

#3 [DOC] swagger 변경사항 수정
  src/main/java/umc/SukBakJi/global/config/SwaggerConfig.java
Labels: docs

#8 [feat] 알람 관련 기능 구현
  .gitignore
  build.gradle
  src/main/java/umc/SukBakJi/domain/controller/CalenderController.java
  src/main/java/umc/SukBakJi/domain/converter/AlarmConverter.java
  src/main/java/umc/SukBakJi/domain/converter/SetUnivConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/AlarmRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/AlarmResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Alarm.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/model/entity/UnivScheduleInfo.java
  src/main/java/umc/SukBakJi/domain/model/entity/University.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/SetUniv.java
  src/main/java/umc/SukBakJi/domain/repository/AlarmRepository.java
  src/main/java/umc/SukBakJi/domain/repository/MemberRepository.java
  src/main/java/umc/SukBakJi/domain/repository/UnivRepository.java
  src/main/java/umc/SukBakJi/domain/service/CalenderService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/application.properties
Labels: feat

#11 [Feat] 연구실 후기 기능 구현
  build.gradle
  src/main/java/umc/SukBakJi/SukBakJiApplication.java
  src/main/java/umc/SukBakJi/domain/controller/LabReviewController.java
  src/main/java/umc/SukBakJi/domain/converter/LabReviewConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/LabReviewCreateDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/LabReviewDetailsDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/LabReviewSearchDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Lab.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/model/entity/ResearchTopic.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/Atmosphere.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/GraduationDifficulty.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/LeadershipStyle.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/SalaryLevel.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/ThesisGuidance.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/LabReview.java
  src/main/java/umc/SukBakJi/domain/repository/LabRepository.java
  src/main/java/umc/SukBakJi/domain/repository/LabReviewRepository.java
  src/main/java/umc/SukBakJi/domain/service/LabReviewService.java
  src/main/java/umc/SukBakJi/global/apiPayload/ApiResponse.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/application.properties
  src/test/java/umc/SukBakJi/domain/service/LabReviewServiceTest.java
Labels: feat

#13 [feat] 게시판 목록, 생성 기능 구현
  .gitignore
  build.gradle
  src/main/java/umc/SukBakJi/domain/controller/BoardController.java
  src/main/java/umc/SukBakJi/domain/model/dto/CreateBoardRequest.java
  src/main/java/umc/SukBakJi/domain/model/entity/Board.java
  src/main/java/umc/SukBakJi/domain/model/entity/BoardLike.java
  src/main/java/umc/SukBakJi/domain/model/entity/Comment.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/model/entity/Post.java
  src/main/java/umc/SukBakJi/domain/model/entity/Reply.java
  src/main/java/umc/SukBakJi/domain/model/entity/Scrap.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/.gitkeep
  src/main/java/umc/SukBakJi/domain/model/entity/enums/Menu.java
  src/main/java/umc/SukBakJi/domain/repository/BoardRepository.java
  src/main/java/umc/SukBakJi/domain/service/BoardService.java
  src/main/resources/application.properties
Labels: feat

#17 [Fix] JWT token Authority error
  src/main/java/umc/SukBakJi/domain/controller/.gitkeep
  src/main/java/umc/SukBakJi/domain/controller/AuthController.java
  src/main/java/umc/SukBakJi/domain/converter/.gitkeep
  src/main/java/umc/SukBakJi/domain/converter/MemberConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/.gitkeep
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/.gitkeep
  src/main/java/umc/SukBakJi/domain/repository/.gitkeep
  src/main/java/umc/SukBakJi/domain/service/.gitkeep
  src/main/java/umc/SukBakJi/domain/service/AuthService.java
  src/main/java/umc/SukBakJi/global/config/SecurityConfig.java
  src/main/java/umc/SukBakJi/global/security/PrincipalDetails.java
  src/main/java/umc/SukBakJi/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/SukBakJi/global/security/jwt/JwtTokenProvider.java
Labels: fix

#20 [Feat] 게시판 메인화면 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/CommunityController.java
  src/main/java/umc/SukBakJi/domain/converter/PostConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/HotBoardPostDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/LatestQuestionDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostListDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Board.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/model/entity/Post.java
  src/main/java/umc/SukBakJi/domain/model/entity/Scrap.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/BoardLike.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/BoardLikeId.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/Scrap.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/ScrapId.java
  src/main/java/umc/SukBakJi/domain/repository/BoardLikeRepository.java
  src/main/java/umc/SukBakJi/domain/repository/PostRepository.java
  src/main/java/umc/SukBakJi/domain/service/CommunityService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/application.properties
Labels: feat

#21 [feat] 박사/석사/진학예정 화면 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/PostController.java
  src/main/java/umc/SukBakJi/domain/model/dto/CreateJobPostRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/CreatePostRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostListResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/model/entity/Post.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/Menu.java
  src/main/java/umc/SukBakJi/domain/repository/BoardRepository.java
  src/main/java/umc/SukBakJi/domain/repository/PostRepository.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
  src/main/resources/application.properties
Labels: feat

#24 [feat] 학교 선택 및 조회 기능 구현 + 알람 관련 기능 수정
  src/main/java/umc/SukBakJi/domain/controller/CalenderController.java
  src/main/java/umc/SukBakJi/domain/converter/AlarmConverter.java
  src/main/java/umc/SukBakJi/domain/converter/SetUnivConverter.java
  src/main/java/umc/SukBakJi/domain/converter/UnivConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/AlarmRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/AlarmResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Alarm.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/SetUniv.java
  src/main/java/umc/SukBakJi/domain/repository/AlarmRepository.java
  src/main/java/umc/SukBakJi/domain/repository/SetUnivRepository.java
  src/main/java/umc/SukBakJi/domain/repository/UnivRepository.java
  src/main/java/umc/SukBakJi/domain/service/CalenderService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/SukBakJi/global/config/SecurityConfig.java
Labels: feat, fix

#26 [Feat] 알람 키기 및 끄기 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/CalenderController.java
  src/main/java/umc/SukBakJi/domain/converter/AlarmConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/AlarmRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/AlarmResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Alarm.java
  src/main/java/umc/SukBakJi/domain/repository/AlarmRepository.java
  src/main/java/umc/SukBakJi/domain/service/CalenderService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
Labels: feat
