Repository SukBakJi/SukBakJi-Server, pull requests merged in 2024-08, with the labels that each got.

#34 [FEAT] 댓글 달기 및 조회 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/CommentController.java
  src/main/java/umc/SukBakJi/domain/controller/PostController.java
  src/main/java/umc/SukBakJi/domain/model/dto/CommentResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/CreateCommentRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Comment.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/repository/CommentRepository.java
  src/main/java/umc/SukBakJi/domain/service/CommentService.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/application.properties
Labels: feat

#32 #31 [Feat] JWT 토큰에서 memberId 추출
  src/main/java/umc/SukBakJi/global/security/jwt/JwtTokenProvider.java
Labels: feat

#36 [Fix] 게시판 파트 memberId -> jwt
  build.gradle
  src/main/java/umc/SukBakJi/domain/controller/AuthController.java
  src/main/java/umc/SukBakJi/domain/controller/CalenderController.java
  src/main/java/umc/SukBakJi/domain/controller/CommentController.java
  src/main/java/umc/SukBakJi/domain/controller/MemberController.java
  src/main/java/umc/SukBakJi/domain/controller/PostController.java
  src/main/java/umc/SukBakJi/domain/converter/AlarmConverter.java
  src/main/java/umc/SukBakJi/domain/converter/MemberConverter.java
  src/main/java/umc/SukBakJi/domain/converter/SetUnivConverter.java
  src/main/java/umc/SukBakJi/domain/converter/UnivConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/AlarmRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/AlarmResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/CreateCommentRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/member/MemberRequestDto.java
  src/main/java/umc/SukBakJi/domain/model/dto/member/MemberResponseDto.java
  src/main/java/umc/SukBakJi/domain/model/entity/Alarm.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/model/entity/ResearchTopic.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/MemberResearchTopic.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/SetUniv.java
  src/main/java/umc/SukBakJi/domain/repository/AlarmRepository.java
  src/main/java/umc/SukBakJi/domain/repository/MemberResearchTopicRepository.java
  src/main/java/umc/SukBakJi/domain/repository/ResearchTopicRepository.java
  src/main/java/umc/SukBakJi/domain/repository/SetUnivRepository.java
  src/main/java/umc/SukBakJi/domain/repository/UnivRepository.java
  src/main/java/umc/SukBakJi/domain/service/AuthService.java
  src/main/java/umc/SukBakJi/domain/service/CalenderService.java
  src/main/java/umc/SukBakJi/domain/service/CommentService.java
  src/main/java/umc/SukBakJi/domain/service/MemberResearchTopicService.java
  src/main/java/umc/SukBakJi/domain/service/MemberService.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/SukBakJi/global/config/SecurityConfig.java
  src/main/java/umc/SukBakJi/global/security/PrincipalDetails.java
  src/main/java/umc/SukBakJi/global/security/jwt/JwtTokenProvider.java
Labels: fix

#37 [Fix] 커뮤니티 메인 홈 기능 JWT 토큰 적용 변경
  src/main/java/umc/SukBakJi/domain/controller/CommunityController.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
Labels: fix

#38 [Feat] Community 기능 구현
  build.gradle
  src/main/java/umc/SukBakJi/domain/controller/CommentController.java
  src/main/java/umc/SukBakJi/domain/controller/CommunityController.java
  src/main/java/umc/SukBakJi/domain/controller/PostController.java
  src/main/java/umc/SukBakJi/domain/converter/PostConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/CommentResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/CreateCommentRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/CreateJobPostRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/CreatePostRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/HotBoardPostDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/LatestQuestionDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostListDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostListResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Board.java
  src/main/java/umc/SukBakJi/domain/model/entity/Comment.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/model/entity/Post.java
  src/main/java/umc/SukBakJi/domain/model/entity/Scrap.java
  src/main/java/umc/SukBakJi/domain/model/entity/enums/Menu.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/BoardLike.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/BoardLikeId.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/Scrap.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/ScrapId.java
  src/main/java/umc/SukBakJi/domain/repository/BoardLikeRepository.java
  src/main/java/umc/SukBakJi/domain/repository/BoardRepository.java
  src/main/java/umc/SukBakJi/domain/repository/CommentRepository.java
  src/main/java/umc/SukBakJi/domain/repository/PostRepository.java
  src/main/java/umc/SukBakJi/domain/service/CommentService.java
  src/main/java/umc/SukBakJi/domain/service/CommunityService.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/application.properties
Labels: feat, fix

#53 [Fix] 연구실 후기 검색 기능 수정
  src/main/java/umc/SukBakJi/domain/controller/LabReviewController.java
  src/main/java/umc/SukBakJi/domain/repository/LabReviewRepository.java
  src/main/java/umc/SukBakJi/domain/service/LabReviewService.java
Labels: fix

#54 [Feat] 연구실 검색, 상세보기 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/LabController.java
  src/main/java/umc/SukBakJi/domain/model/dto/LabDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/LabResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/SearchLabRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Lab.java
  src/main/java/umc/SukBakJi/domain/model/entity/ResearchTopic.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/LabResearchTopic.java
  src/main/java/umc/SukBakJi/domain/repository/LabRepository.java
  src/main/java/umc/SukBakJi/domain/service/LabService.java
Labels: feat

#60 #59 [Feat] 사용자 관심 연구 주제 목록 모아보기 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/LabController.java
  src/main/java/umc/SukBakJi/domain/model/dto/InterestTopicDTO.java
  src/main/java/umc/SukBakJi/domain/service/LabService.java
Labels: feat

#63 #61 [Fix] 사용자 관심 연구주제 모아보기 응답 형식 수정
  src/main/java/umc/SukBakJi/domain/controller/LabController.java
  src/main/java/umc/SukBakJi/domain/model/dto/InterestTopicsDTO.java
  src/main/java/umc/SukBakJi/domain/service/LabService.java
Labels: fix

#65 [feat] 남은 캘린더 관련 기능 구현 및 jwt 토큰 적용
  src/main/java/umc/SukBakJi/domain/controller/CalenderController.java
  src/main/java/umc/SukBakJi/domain/converter/UnivConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/UnivScheduleInfo.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/SetUniv.java
  src/main/java/umc/SukBakJi/domain/repository/SetUnivRepository.java
  src/main/java/umc/SukBakJi/domain/repository/UnivScheduleInfoRepository.java
  src/main/java/umc/SukBakJi/domain/service/CalenderService.java
Labels: feat, fix, refactor

#66 #27 [Fix] SetUniv Entity 중 showing 수정
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/SetUniv.java
Labels: fix

#69 #68[feat]: 게시판 즐겨찾기/스크랩 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/BoardController.java
  src/main/java/umc/SukBakJi/domain/controller/ScrapController.java
  src/main/java/umc/SukBakJi/domain/repository/BoardLikeRepository.java
  src/main/java/umc/SukBakJi/domain/repository/ScrapRepository.java
  src/main/java/umc/SukBakJi/domain/service/BoardService.java
  src/main/java/umc/SukBakJi/domain/service/ScrapService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
Labels: feat

#76 [Feat] 멘토 관련 API 기능
  src/main/java/umc/SukBakJi/domain/controller/MentoringController.java
  src/main/java/umc/SukBakJi/domain/converter/MentoringConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/MentoringRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/MentoringResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Mentor.java
  src/main/java/umc/SukBakJi/domain/model/entity/mapping/Mentoring.java
  src/main/java/umc/SukBakJi/domain/repository/MentorRepository.java
  src/main/java/umc/SukBakJi/domain/repository/MentoringRepository.java
  src/main/java/umc/SukBakJi/domain/service/MentoringService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
Labels: feat

#79 #78 [Feat] 사용자 id 조회 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/CalenderController.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivResponseDTO.java
Labels: feat

#81 [Feat] 멘토링 관련 기능
  src/main/java/umc/SukBakJi/domain/controller/CalenderController.java
  src/main/java/umc/SukBakJi/domain/controller/MentoringController.java
  src/main/java/umc/SukBakJi/domain/converter/MentoringConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/MentoringRequestDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/MentoringResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/UnivResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/entity/Member.java
  src/main/java/umc/SukBakJi/domain/repository/LabRepository.java
  src/main/java/umc/SukBakJi/domain/repository/LabResearchTopicRepository.java
  src/main/java/umc/SukBakJi/domain/repository/MemberRepository.java
  src/main/java/umc/SukBakJi/domain/repository/ResearchTopicRepository.java
  src/main/java/umc/SukBakJi/domain/service/CalenderService.java
  src/main/java/umc/SukBakJi/domain/service/MentoringService.java
Labels: feat, fix

#83 #82 [Feat] 게시글 검색 기능 구현
  src/main/java/umc/SukBakJi/domain/controller/CommunityController.java
  src/main/java/umc/SukBakJi/domain/converter/PostConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostSearchDTO.java
  src/main/java/umc/SukBakJi/domain/repository/PostRepository.java
  src/main/java/umc/SukBakJi/domain/service/CommunityService.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
Labels: feat

#87 #86[fix]:게시글 상세보기,목록에 지원분야,채용형태 추가
  src/main/java/umc/SukBakJi/domain/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostListResponseDTO.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
Labels: fix

#90 #89 [Fix] Hot 게시판 postId 반환
  src/main/java/umc/SukBakJi/domain/converter/PostConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/HotBoardPostDTO.java
Labels: fix

#91 #88[fix]: 게시글 상세보기에 멤버 아이디 추가
  src/main/java/umc/SukBakJi/domain/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
Labels: fix

#93 return memberid in comment feature
  src/main/java/umc/SukBakJi/domain/model/dto/CommentResponseDTO.java
  src/main/java/umc/SukBakJi/domain/service/CommentService.java
Labels: fix

#95 연구실 상세보기에서 교수 이메일 추가 반환
  src/main/java/umc/SukBakJi/domain/model/dto/LabDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/service/LabService.java
Labels: fix

#97 #96[fix]: post detail fix
  src/main/java/umc/SukBakJi/domain/service/CommentService.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
Labels: fix

#98 Merge to main
  src/main/java/umc/SukBakJi/domain/converter/PostConverter.java
  src/main/java/umc/SukBakJi/domain/converter/UnivConverter.java
  src/main/java/umc/SukBakJi/domain/model/dto/CommentResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/HotBoardPostDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/LabDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/model/dto/PostListResponseDTO.java
  src/main/java/umc/SukBakJi/domain/service/CommentService.java
  src/main/java/umc/SukBakJi/domain/service/LabService.java
  src/main/java/umc/SukBakJi/domain/service/MentoringService.java
  src/main/java/umc/SukBakJi/domain/service/PostService.java
Labels: feat
