Repository SukBakJi/SukBakJi-Server, pull requests merged in 2025-04, with the labels that each got.

#204 fix: 댓글에 commentId 추가 및 글쓴이 댓글 처리 로직 수정
  src/main/java/umc/SukBakJi/domain/board/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/board/service/PostService.java
Labels: fix

#205 fix: 댓글에 commentId 추가 및 글쓴이 댓글 처리 로직 수정
  src/main/java/umc/SukBakJi/domain/board/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/board/service/PostService.java
Labels: fix

#206 fix: 댓글에 memberId추가
  src/main/java/umc/SukBakJi/domain/board/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/board/service/PostService.java
Labels: fix

#207 fix: 게시글 불러오기 속 댓글내용에 memberId 추가
  src/main/java/umc/SukBakJi/domain/board/model/dto/PostDetailResponseDTO.java
  src/main/java/umc/SukBakJi/domain/board/service/PostService.java
Labels: fix

#219 feat: 게시글 삭제 기능 추가
  src/main/java/umc/SukBakJi/domain/board/controller/PostController.java
  src/main/java/umc/SukBakJi/domain/board/service/PostService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
Labels: feat

#232 Feat/231
  src/main/java/umc/SukBakJi/domain/block/controller/BlockController.java
  src/main/java/umc/SukBakJi/domain/block/model/dto/BlockResponseDto.java
  src/main/java/umc/SukBakJi/domain/block/model/entity/MemberBlock.java
  src/main/java/umc/SukBakJi/domain/block/repository/BlockRepository.java
  src/main/java/umc/SukBakJi/domain/block/service/BlockService.java
  src/main/java/umc/SukBakJi/domain/board/controller/PostController.java
  src/main/java/umc/SukBakJi/domain/board/repository/PostRepository.java
  src/main/java/umc/SukBakJi/domain/board/service/PostService.java
Labels: feat

#235 [FEAT] 비속어 필터링 구현
  src/main/java/umc/SukBakJi/domain/board/controller/PostController.java
  src/main/java/umc/SukBakJi/domain/board/service/BoardService.java
  src/main/java/umc/SukBakJi/domain/board/service/CommentService.java
  src/main/java/umc/SukBakJi/domain/board/service/PostService.java
  src/main/java/umc/SukBakJi/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/SukBakJi/global/filter/BadWordFilter.java
  src/main/resources/badwords.txt
  src/test/java/umc/SukBakJi/global/filter/BadWordFilterTest.java
Labels: feat

#238 [REFACTOR] 전반적인 코드 리펙토링
  src/main/java/umc/SukBakJi/domain/alarm/controller/AlarmController.java
  src/main/java/umc/SukBakJi/domain/auth/controller/AuthController.java
  src/main/java/umc/SukBakJi/domain/auth/controller/SmsController.java
  src/main/java/umc/SukBakJi/domain/block/controller/BlockController.java
  src/main/java/umc/SukBakJi/domain/board/controller/BoardController.java
  src/main/java/umc/SukBakJi/domain/board/controller/CommentController.java
  src/main/java/umc/SukBakJi/domain/board/controller/CommunityController.java
  src/main/java/umc/SukBakJi/domain/board/controller/PostController.java
  src/main/java/umc/SukBakJi/domain/board/controller/ReportController.java
  src/main/java/umc/SukBakJi/domain/board/controller/ScrapController.java
  src/main/java/umc/SukBakJi/domain/lab/controller/LabController.java
  src/main/java/umc/SukBakJi/domain/lab/controller/LabReviewController.java
  src/main/java/umc/SukBakJi/domain/lab/controller/ResearchTopicController.java
  src/main/java/umc/SukBakJi/domain/member/controller/MemberController.java
  src/main/java/umc/SukBakJi/domain/mentoring/controller/MentoringController.java
  src/main/java/umc/SukBakJi/domain/university/controller/CalenderController.java
Labels: refactor
